### ISSUE TITLE
Data format covariance matrix

### ISSUE THREAD

**Issue by andrewcztrack** [twistedcubic/coin-press#1]
Hi @hoonose @twistedcubic ,
I really like this work!
I am just wondering how to format the array if i have a nxd numpy array.
How best to format it for the covariance estimation.
I cant seem to get the torch format correct.
Best,
Andrew

**Comment by twistedcubic** [comment]
Hi Andrew,

We are glad you are interested!

The format of an `n x  d` array is correct for [covariance estimation](https://github.com/twistedcubic/coin-press/blob/master/algos.py#L49). To turn the numpy array into a torch tensor, call `torch.from_numpy(your_array)`, and use this tensor for the covariance estimation.

**Comment by hoonose** [comment]
Ditto -- thanks for the kind words! Like Yihe confirmed, each datapoint is one row and each dimension is a column. A minimal code snippest is below, where the dataset is generated from both PyTorch and NumPy, so you can see the difference. Like Yihe said, you convert using `torch.from_numpy()`. But I was surprised to see that you have to add a `.float()` to end to convert it to the appropriate format (despite the fact that the error message it was giving me said the opposite...). Anyway, let us know if this helps, or if not we're happy to help debug/clarify!

```python
import utils
import torch
import numpy as np
from algos import *

args = utils.parse_args()
args.d = 10
dist_mean = torch.zeros(args.d)
dist_cov = torch.eye(args.d)
args.u = 10*np.sqrt(args.d)
args.total_budget = .5
args.t = 3
args.rho = [(1.0/8.0)*args.total_budget, (1.0/8.0)*args.total_budget, (3.0/4.0)*args.total_budget]
args.n = 5000

X_torch = torch.distributions.MultivariateNormal(dist_mean, dist_cov).sample((args.n,))
Sigma_torch = cov_est(X_torch.clone(), args)
print(Sigma_torch)

X_numpy = torch.from_numpy(np.random.multivariate_normal(dist_mean, dist_cov, args.n)).float()
Sigma_numpy = cov_est(X_numpy, args)
print(Sigma_numpy)
```

**Comment by andrewcztrack** [comment]
Hi @hoonose @twistedcubic Thank you so much for your support! I sincerely appreciate it! you both are absolute heroes and are very generous with your time. I am trying to create a rolling covariance matrix.

The below code is what i have.

so I have two array of arrays.

```python

residarray=[len(ll)]



for i, j in zip(ll,ll2):
    i=i.reshape(len(i),1)
    j=j.reshape(len(j),1)
    residarray.append(np.concatenate((i,j), axis=1))
    

cov_test=torch.from_numpy(residarray[6]).float()
cov_test

import utils
import torch
import numpy as np
from algos import *

args = utils.parse_args()
args.d = 10
dist_mean = torch.zeros(args.d)
dist_cov = torch.eye(args.d)
args.u = 10*np.sqrt(args.d)
args.total_budget = .5
args.t = 3
args.rho = [(1.0/8.0)*args.total_budget, (1.0/8.0)*args.total_budget, (3.0/4.0)*args.total_budget]
args.n = 5000


Sigma_numpy = cov_est(cov_test, args)
```

**Comment by andrewcztrack** [comment]
but i am getting the error

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-b9c2950e67e0> in <module>
     72 
     73 
---> 74 Sigma_numpy = cov_est(cov_test, args)

~/coin-press/algos.py in cov_est(X, args)
     56 
     57     for i in range(args.t-1):
---> 58         A, Z = cov_est_step(X, A, args.rho[i], i, args)
     59     A_t, Z_t = cov_est_step(X, A, args.rho[-1], args.t-1, args)
     60 

~/coin-press/algos.py in cov_est_step(X, A, rho, cur_iter, args)
     13     One step of multivariate covariance estimation, scale cov a.
     14     """
---> 15     W = torch.mm(X, A)
     16     n = args.n
     17     d = args.d

RuntimeError: size mismatch, m1: [30 x 2], m2: [10 x 10] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
```

**Comment by twistedcubic** [comment]
Hi Andrew, this is due to `args.d` not being updated for the current dataset being examined in your rolling covariance matrix experiment. Try setting `args.d` depending on the dataset used at a given time.

**Comment by andrewcztrack** [comment]
ah! of course! apologies! i changed it and it worked!
Thank you!
This issue can now be considered closed.
