### ISSUE TITLE
strange mean values.

### ISSUE THREAD

**Issue by andrewcztrack** [twistedcubic/coin-press#2]
Hi @hoonose @twistedcubic !!
i am now trying to find the mean calculation of a nx1 array.
i am trying to calculate it but i am getting strange values.
Would it be possible to provide a small example.

kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
for example the below -
```python

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
import time
import random
from algos import *
from scipy import stats
from utils import fineMeanEst, privateRangeEst, twoShot
import datetime
import yfinance as yf
start_date = datetime.datetime.now() - datetime.timedelta(days=5000)
end_date = datetime.date.today()
df = yf.download('GOOGL', start=start_date, end=end_date)['Close']
test=df.to_numpy()
test=test.reshape(len(test),1)
X=test
#Headline experiments. Vary n. Fix parameters d = 50, r = 10*sqrt(d), rho = 0.5. t = 1 through 4.

d = 1
mean = [0.0]*d
cov = np.eye(d)
c = [0]*d
r = 10*np.sqrt(d)
p = 0.5
eps = np.sqrt(2.0*p)

Ps1 = [p]
Ps2 = [(1.0/4.0)*p, (3.0/4.0)*p]

print(L2(multivariate_mean_iterative(X.copy(), c, r, 2, Ps2)-mean))
print(np.mean(X))

[*********************100%***********************]  1 of 1 completed
13.20941027320505
598.3095816613904

```

How could be such a difference in values?

**Comment by hoonose** [comment]
Hi Andrew, I recommend you take a look at the role of the parameters c and r. When you run our code, you are implicitly assuming three things:
1. The data is sub-Gaussian
2. The data has variance 1
3. The mean mu of the distribution the data comes from has the property that |c - mu| < r

Based on your specific instance, I infer that you're running this with stock prices for GOOGL. The first assumption might be OK -- even if it isn't, it's probably robust to that. The second and third assumptions are not true in this case. For the second: I took a look at the GOOGL price for the last 5k days, and it seems to be between 200 and 1700. Definitely not variance = 1. You're supposed to run the variance estimation algorithm first, and then plug in the value here. Similarly, with the parameters set as-is, you're saying that the mean of the distribution is within 10 of 0. This is not true.

Off the top of my head, if you wanted it to work in this case, I would try swapping in these three settings of parameters:
```
cov = math.pow(1000, 2)*np.eye(d)
c = [1000]*d
r = 1000
```

I'm just taking a guess with the setting of `cov`, you should really use the covariance estimation algorithm first.

**Comment by andrewcztrack** [comment]
ahhh thank you @hoonose !!! very interesting!!!!
so is this mean an improvement on the regular calculation for the mean.
ie more robust to out of sample data?

Kind regards and thanks,
Andrew

**Comment by hoonose** [comment]
The purpose of this code is to handle weaker a priori bounds on where the unknown parameters lie. Please see the paper (https://arxiv.org/abs/2006.06618) or a talk video (https://www.youtube.com/watch?v=5A6RD9NVqdI) for furhter detail.
